### ISSUE TITLE
Add lib on luarocks

### ISSUE THREAD

**Issue by mauricioabreu** [jkeys089/lua-resty-resolver#14]
Hello, thank you for this library.

Do you intend to have this library stored on luarocks repository? If so, how can I help you to achieve it?

**Comment by jkeys089** [comment]
@mauricioabreu I don't personally use luarocks but I'd be happy to merge a PR / work with you to get it published if you think it would be helpful.

**Comment by mauricioabreu** [comment]
@jkeys089 thank you!

I will create a new PR with all the configuration needed to publish it on luarocks.

**Comment by mauricioabreu** [comment]
PR opened! Thank you.

**Comment by jkeys089** [comment]
@mauricioabreu thanks for the contribution!
