### ISSUE TITLE
"no hosts available" error

### ISSUE THREAD

**Issue by mauricioabreu** [jkeys089/lua-resty-resolver#18]
Hello,

I'm having this error in some of my logs. My cluster has more than 30 servers and 2 or 3 have this error.

Source code: https://github.com/jkeys089/lua-resty-resolver/blob/49eb31b2e7eb9e0c94d0363fc885ab65a57d4327/lib/resolver/client.lua#L90

Reading the code, I could not catch what is causing this specific error. Did you already have this error?

**Comment by mauricioabreu** [comment]
It looks like it is not re-syncing:

https://github.com/jkeys089/lua-resty-resolver/blob/49eb31b2e7eb9e0c94d0363fc885ab65a57d4327/lib/resolver/client.lua#L83

**Comment by jkeys089** [comment]
@mauricioabreu Could you provide some sample code where you're receiving this error? I suspect you're not allowing stale results (the default behavior). If there is an error querying DNS or if there aren't any valid records it is possible for cached records to expire which would cause the `no hosts available` error. Depending on your needs  you could explicitly allow stale records to help smooth over DNS errors / outages.

**Comment by mauricioabreu** [comment]
Thank you for your detailed answer @jkeys089 and I'm sorry for not providing my source code earlier.

Here are the most important parts:

```lua
 -- initialize DNS master resolver
    google_master_dns = dns_resolver.new_master{
      cache="dns_cache",
      upstream_domain="dai.google.com",
      dns_servers={
        "dns1_server.example.com",
        "dns2_server.example.com",
        "dns3_server.example.com",
        "dns4_server.example.com"
      }
    }

-- initialize DNS client resolver
google_client_dns = dns_resolver.new_client(google_master_dns)
```

```lua
upstream google_dai {
    server 0.0.0.1; # just an invalid address as a place holder

    balancer_by_lua_block {
      local ok, err = dns_resolver.set_address(
        google_client_dns, {exp_fallback_ok = true, port = "443"}
      )
      if not ok then
        ngx.log(ngx.ERR, "failed to set upstream address: ", err)
        return ngx.exit(ngx.HTTP_INTERNAL_SERVER_ERROR)
      end
    }
    keepalive 100; # connection pool MUST come after balancer_by_lua_block
  }
```

```lua
local dns_resolver = {}

dns_resolver.new_master = function(args)
  local master, err = require("resolver.master"):new(args.cache, args.upstream_domain, args.dns_servers)
  if not master then
    ngx.log(ngx.ERR, "failed to google resolver master: " .. err)
  end
  return master
end

dns_resolver.new_client = function(master)
  master:init()
  local client, err = master:client()
  if not client then
    ngx.log(ngx.ERR, "failed to create hello resolver client: " .. err)
  end
  return client
end

dns_resolver.set_address = function(client, options)
  local upstream_address_ip, err = client:get(options.exp_fallback_ok)
  if not upstream_address_ip then
    return false, err
  end

  local ok, err = require("ngx.balancer").set_current_peer(upstream_address_ip, options.port)
  if not ok then
    return false, err
  end

  return true, nil
end

return dns_resolver
```

**Comment by jkeys089** [comment]
@mauricioabreu I think your `dns_resolver.new_client` function needs to be called in a `init_worker_by_lua_block` (see: https://github.com/jkeys089/lua-resty-resolver#master-init).

**Comment by mauricioabreu** [comment]
@jkeys089 I forgot to add the block while pasting but it was already there.

```lua
init_by_lua_block {
     -- initialize DNS master resolver
        google_master_dns = dns_resolver.new_master{
          cache="dns_cache",
          upstream_domain="dai.google.com",
          dns_servers={
            "dns1_server.example.com",
            "dns2_server.example.com",
            "dns3_server.example.com",
            "dns4_server.example.com"
          }
        }

    -- initialize DNS client resolver
    google_client_dns = dns_resolver.new_client(google_master_dns)
}

init_worker_by_lua_block {
    -- initialize DNS client resolver
    google_client_dns = dns_resolver.new_client(google_master_dns)
}
```

**Comment by jkeys089** [comment]
@mauricioabreu It should *only* be in the `init_worker_by_lua_block` -- subsequent calls after the first have no impact.

**Comment by mauricioabreu** [comment]
@jkeys089 Sorry I'm having a hard day.

Again it was a copy/paste problem.

```lua
init_by_lua_block {
     -- initialize DNS master resolver
        google_master_dns = dns_resolver.new_master{
          cache="dns_cache",
          upstream_domain="dai.google.com",
          dns_servers={
            "dns1_server.example.com",
            "dns2_server.example.com",
            "dns3_server.example.com",
            "dns4_server.example.com"
          }
        }
}

init_worker_by_lua_block {
    -- initialize DNS client resolver
    google_client_dns = dns_resolver.new_client(google_master_dns)
}
```

**Comment by mauricioabreu** [comment]
Could it be a network/firewall problem, right? I am trying to isolate all my servers with problems to check why they behave this way with the very same code.

**Comment by jkeys089** [comment]
Could be -- I believe there should be something in your logs like `resolver master failed ...` if this was the case.

**Comment by mauricioabreu** [comment]
@jkeys089 thank you! I'm going to collect more logs to make debugging easier.

**Comment by mauricioabreu** [comment]
@jkeys089 after debugging my code, I noticed that it is not raising an error like the one in the docs:

From the README.md

```
 init_by_lua_block {
            local err
            cdnjs_master, err = require("resolver.master"):new("dns_cache", "cdnjs.cloudflare.com", {"8.8.8.8"})
            if not cdnjs_master then
                error("failed to create cdnjs resolver master: " .. err)
            end
        }
```

Should I raise this `error`?

**Comment by jkeys089** [comment]
@mauricioabreu you should definitely handle this error somehow (e.g. log, retry, etc...).

**Comment by mauricioabreu** [comment]
@jkeys089 thank you! Closing this issue because this is probably my problem.
