### ISSUE TITLE
Adding many domains

### ISSUE THREAD

**Issue by geemang2000** [jkeys089/lua-resty-resolver#2]
Awesome library btw. Most of the other libs require resolves in every location block. I like how this is taken care of in the background. 

1. Is there a recommended practice to add many domain names?  
Do we call this repeatability? cdnjs_master, err = require("resolver.master"):new("dns_cache", 'domain', ...)
1. what does this mean?  (may be shared for multiple domains but for best perf use separate zone per domain) - use a separate lua_shared_dict dns_cache 1m  for each domain?

**Comment by jkeys089** [comment]
> Is there a recommended practice to add many domain names?
> Do we call this repeatability? cdnjs_master, err = require("resolver.master"):new("dns_cache", 'domain', ...)

You just need to create a separate `master` instance for each domain.
e.g.
```lua
local err
local resolver_master = require "resolver.master"

domain1_master, err = resolver_master:new("dns_cache", "aaa.example.com", {"8.8.8.8"})
if not domain1_master then
    error("failed to create domain1 resolver master: " .. err)
end

domain2_master, err = resolver_master:new("dns_cache", "bbb.example.com", {"8.8.8.8"})
if not domain1_master then
    error("failed to create domain1 resolver master: " .. err)
end

domain3_master, err = resolver_master:new("dns_cache", "ccc.example.com", {"8.8.8.8"})
...
```

> what does this mean? (may be shared for multiple domains but for best perf use separate zone per domain) - use a separate lua_shared_dict dns_cache 1m for each domain?

Correct. The reason you *might* want to use a separate `lua_shared_dict` per domain is to reduce cache contention. The shared memory zone is used by the master instance to cache DNS resolution results amongst all nginx worker threads. Each client instance also keeps a local cache but it periodically syncs from the shared memory zone to be sure it has fresh / accurate data. We actually randomize the shared memory access to try and minimize contention but it *could* create a bottleneck with a lot of domains, a lot of worker processes, and very low DNS TTL values.

It is perfectly fine to use the same `lua_shared_dict` if:
*  you run in a single-threaded environment
*  you force a large minimum TTL value
*  you test and find that your performance is OK or your performance bottleneck exists somewhere else in the application *(highly likely)*

In the end, it all boils down to your usage pattern. Under normal circumstances the shared memory zone will likely never be your bottleneck. However, if you have a bunch of domains with lots of worker processes and very small TTL values then you'd be better off using multiple shared memory zones to help relieve contention.

I hope that helps!
