### ISSUE TITLE
Stops working after an nginx reload

### ISSUE THREAD

**Issue by essh** [jkeys089/lua-resty-resolver#6]
When nginx is reloaded (with a HUP signal) the timers that perform DNS resolution no longer continue to fire so none of the shared dict entries get updated and things start to fail as TTLs expire.

This seems to be because the timer responsible for updating these is created in one worker (and this is ensured by only doing so when a `_master_` entry is successfully added to the shared_key).

However, the problem with this seems to be the following from the lua-nginx-module documentation _"But note that, the lua_shared_dict's shm storage will not be cleared through a config reload (via the HUP signal, for example)."_ As such, since these `_master_` entries still exist in the shared dict and the timers don't get recreated in the new workers that are replacing the old ones.

I've managed to work around this problem in some very limited testing with a one line fix in https://github.com/essh/lua-resty-resolver/commit/fde6e43f95901e596b6eb6c2032be41c246a2868. However, I'm not entirely sure if this is the best approach and any feedback regarding this would be appreciated. Primarily, it seems like there is some potential for race conditions during the reload process whilst both the new and old worker processes continue to exist.

**Comment by jkeys089** [comment]
@essh Great catch! I think your solution looks great and would not cause any race conditions since the `master:new` method should be invoked in a `init_by_lua_block` which is guaranteed to happen only once 
> on the global Lua VM level when the Nginx master process (if any) is loading the Nginx config file

If you want to send a PR I'll merge straight away and publish the new version to OPM. Thanks again!
