### ISSUE TITLE
Master resolver dies after expire time when initialized within cache-loader process

### ISSUE THREAD

**Issue by omonar** [jkeys089/lua-resty-resolver#9]
I have experienced a "random" dies of master resolver. Namely, the master correctly resolves the IP address when it is initialized, for example,
`2020/02/01 13:14:45 [notice] 30880#30880: *2 [lua] master.lua:167: set(): address: XX.XX.XX.XX, ttl: 20, context: ngx.timer`
`2020/02/01 13:14:45 [notice] 30880#30880: *2 [lua] master.lua:23: schedule(): next lookup in 18s, context: ngx.timer`
and then it dies. The master resolver is not executed again.

I believe I managed to identify the conditions when master resolver "dies." My configuration involves proxy cache zone. When master resolver assigns itself to a cache-loader process (pid 30880), it "dies" because cache-loader process is stopped after 1 minute. See the outcome of `ps aux` below
`root      30876  0.0  0.1  62580  1204 ?        Ss   13:14   0:00 nginx: master process /usr/sbin/nginx -g daemon on; master_process on;`
`www-data  30877  0.0  0.4  66960  4312 ?        S    13:14   0:00 nginx: worker process`
`www-data  30878  0.0  0.4  66960  4312 ?        S    13:14   0:00 nginx: worker process`
`www-data  30879  0.0  0.4  66960  4088 ?        S    13:14   0:00 nginx: cache manager process`
`www-data  30880  0.0  0.4  66960  4088 ?        S    13:14   0:00 nginx: cache loader process`

If understood correctly, the master resolver is assigned to the first worker that is initialized. If this happens to be a cache-loader process, then, well, it is doomed. There are no problems when master resolver is assigned to actual worker process or even cache-manager process because they run continuously.

**Comment by jkeys089** [comment]
@omonar interesting. I'm actually not familiar with the cache loader process. I'll do some reading to see if I can determine how to avoid initializing the master in that process. In the meantime, do you happen to have a sample config I could use to try and recreate the issue?

**Comment by omonar** [comment]
@jkeys089 sample config attached [test.txt](https://github.com/jkeys089/lua-resty-resolver/files/4144067/test.txt). I have not mentioned it earlier but I experienced the issue on Ubuntu 18.04 with nginx 1.14.0 and libnginx-mod-http-lua. Strangely, I have not been able to reproduce the issue with the latest version of openresty (1.15.8.2).

**Comment by omonar** [comment]
@jkeys089 I made a quick test. The following [patch](https://github.com/omonar/lua-resty-resolver/commit/8dfb3331e76658f17201e790a0b17073cf9bf75e) resolves the issue.
